# Generated by Django 4.1 on 2023-12-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_alter_voting_postproc_alter_voting_tally'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('SI_NO', 'Binario'), ('RANKING', 'Ranking'), ('NORMAL', 'Normal')], default='NORMAL', max_length=10),
        ),
        migrations.AddField(
            model_name='voting',
            name='ranked',
            field=models.BooleanField(default=False),
        ),
    ]
